Automate the extraction of CRD versions for helm

diff --git a/.github/workflows/nodes-plan-apply.yaml b/.github/workflows/nodes-plan-apply.yaml
--- a/.github/workflows/nodes-plan-apply.yaml
+++ b/.github/workflows/nodes-plan-apply.yaml
@@ -112,6 +112,26 @@ jobs:
           echo "Applying plan"
           terraform apply -lock-timeout=5m "${PLAN_FILE}"
 
+      - name: Install helm
+        uses: azure/setup-helm@v4.3.1
+        with:
+          version: "v4.0.0"
+
+      - name: Regenerate API versions
+        shell: bash
+        run: |
+          set -euo pipefail
+          # TODO: Install yq properly with caching and versioning.
+          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
+          sudo chmod +x /usr/local/bin/yq
+
+          ./charts/extract-apis/generate-api-versions.sh
+          # Check for changes (warn only, don't fail)
+          if ! git diff --exit-code ; then
+            echo "::warning title=API Versions Changed::API versions or kube version have changed. Consider committing the updated files."
+            git diff charts/extract-apis/helm-api-versions.txt charts/extract-apis/helm-kube-version.txt
+          fi
+
       - name: De-wireguard
         if: always()
         run: |
